-- 多商户电商平台 P0 版本数据库表结构
-- Target: MySQL 8.x / InnoDB / utf8mb4
-- 说明：
-- 1. 金额统一 DECIMAL(18,2)，状态统一 VARCHAR(32)。
-- 2. 所有核心业务表包含 deleted_at、created_at、updated_at、version。
-- 3. P0 使用数据库外键表达核心关系；若后续分库分表，可迁移为应用层逻辑外键。

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT NOT NULL COMMENT '用户ID',
  mobile VARCHAR(20) NOT NULL COMMENT '手机号',
  password_hash VARCHAR(255) NULL COMMENT '密码哈希',
  nickname VARCHAR(64) NULL COMMENT '昵称',
  avatar_url VARCHAR(500) NULL COMMENT '头像URL',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED, DISABLED',
  last_login_at DATETIME(3) NULL COMMENT '最后登录时间',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_users_mobile (mobile),
  KEY idx_users_status (status),
  KEY idx_users_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户表';

CREATE TABLE IF NOT EXISTS user_addresses (
  id BIGINT NOT NULL COMMENT '地址ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  receiver_name VARCHAR(64) NOT NULL COMMENT '收货人',
  receiver_mobile VARCHAR(20) NOT NULL COMMENT '收货手机号',
  province VARCHAR(64) NOT NULL COMMENT '省',
  city VARCHAR(64) NOT NULL COMMENT '市',
  district VARCHAR(64) NOT NULL COMMENT '区县',
  detail_address VARCHAR(255) NOT NULL COMMENT '详细地址',
  is_default TINYINT NOT NULL DEFAULT 0 COMMENT '是否默认地址',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED, DISABLED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  KEY idx_user_addresses_user (user_id),
  CONSTRAINT fk_user_addresses_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户收货地址表';

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT NOT NULL COMMENT '类目ID',
  parent_id BIGINT NULL COMMENT '父级类目ID',
  category_name VARCHAR(64) NOT NULL COMMENT '类目名称',
  level INT NOT NULL DEFAULT 1 COMMENT '层级',
  sort_no INT NOT NULL DEFAULT 0 COMMENT '排序',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED, DISABLED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  KEY idx_categories_parent (parent_id),
  KEY idx_categories_status (status),
  CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品类目表';

CREATE TABLE IF NOT EXISTS merchants (
  id BIGINT NOT NULL COMMENT '商家ID',
  merchant_no VARCHAR(64) NOT NULL COMMENT '商家编号',
  owner_user_id BIGINT NOT NULL COMMENT '老板用户ID',
  company_name VARCHAR(128) NOT NULL COMMENT '主体名称',
  license_no VARCHAR(64) NOT NULL COMMENT '营业执照号',
  contact_name VARCHAR(64) NOT NULL COMMENT '联系人',
  contact_mobile VARCHAR(20) NOT NULL COMMENT '联系电话',
  audit_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, APPROVED, REJECTED',
  status VARCHAR(32) NOT NULL DEFAULT 'DISABLED' COMMENT 'ENABLED, FROZEN, DISABLED',
  reject_reason VARCHAR(500) NULL COMMENT '驳回原因',
  approved_at DATETIME(3) NULL COMMENT '审核通过时间',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_merchants_no (merchant_no),
  UNIQUE KEY uk_merchants_license_no (license_no),
  KEY idx_merchants_owner (owner_user_id),
  KEY idx_merchants_status (status, audit_status),
  CONSTRAINT fk_merchants_owner_user FOREIGN KEY (owner_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商家主体表';

CREATE TABLE IF NOT EXISTS stores (
  id BIGINT NOT NULL COMMENT '店铺ID',
  merchant_id BIGINT NOT NULL COMMENT '商家ID',
  store_no VARCHAR(64) NOT NULL COMMENT '店铺编号',
  store_name VARCHAR(128) NOT NULL COMMENT '店铺名称',
  logo_url VARCHAR(500) NULL COMMENT 'Logo URL',
  contact_mobile VARCHAR(20) NULL COMMENT '店铺联系电话',
  category_id BIGINT NULL COMMENT '主营类目ID',
  status VARCHAR(32) NOT NULL DEFAULT 'DISABLED' COMMENT 'ENABLED, FROZEN, CLOSED, DISABLED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_stores_no (store_no),
  UNIQUE KEY uk_stores_merchant (merchant_id),
  KEY idx_stores_status (status),
  KEY idx_stores_category (category_id),
  CONSTRAINT fk_stores_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id),
  CONSTRAINT fk_stores_category FOREIGN KEY (category_id) REFERENCES categories (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='店铺表';

CREATE TABLE IF NOT EXISTS merchant_staffs (
  id BIGINT NOT NULL COMMENT '商家员工ID',
  merchant_id BIGINT NOT NULL COMMENT '商家ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  staff_name VARCHAR(64) NOT NULL COMMENT '员工姓名',
  role_type VARCHAR(32) NOT NULL COMMENT 'OWNER, STAFF',
  menu_permissions JSON NULL COMMENT '菜单权限编码列表',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED, DISABLED',
  last_login_at DATETIME(3) NULL COMMENT '最后登录时间',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_staff_merchant_user (merchant_id, user_id),
  KEY idx_staff_user (user_id),
  KEY idx_staff_merchant_status (merchant_id, status),
  CONSTRAINT fk_staff_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id),
  CONSTRAINT fk_staff_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商家员工表';

CREATE TABLE IF NOT EXISTS products (
  id BIGINT NOT NULL COMMENT '商品ID',
  product_no VARCHAR(64) NOT NULL COMMENT '商品编号',
  merchant_id BIGINT NOT NULL COMMENT '商家ID',
  store_id BIGINT NOT NULL COMMENT '店铺ID',
  category_id BIGINT NOT NULL COMMENT '类目ID',
  product_name VARCHAR(255) NOT NULL COMMENT '商品名称',
  main_image_url VARCHAR(500) NULL COMMENT '主图URL',
  detail_html MEDIUMTEXT NULL COMMENT '商品详情HTML',
  audit_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, APPROVED, REJECTED',
  sale_status VARCHAR(32) NOT NULL DEFAULT 'OFF_SALE' COMMENT 'ON_SALE, OFF_SALE',
  reject_reason VARCHAR(500) NULL COMMENT '驳回原因',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_products_no (product_no),
  KEY idx_products_store_status (store_id, sale_status, audit_status),
  KEY idx_products_merchant_status (merchant_id, sale_status, audit_status),
  KEY idx_products_category (category_id),
  KEY idx_products_name (product_name),
  FULLTEXT KEY ft_products_search (product_name, detail_html),
  CONSTRAINT fk_products_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id),
  CONSTRAINT fk_products_store FOREIGN KEY (store_id) REFERENCES stores (id),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品SPU表';

CREATE TABLE IF NOT EXISTS product_skus (
  id BIGINT NOT NULL COMMENT 'SKU ID',
  sku_no VARCHAR(64) NOT NULL COMMENT 'SKU编号',
  product_id BIGINT NOT NULL COMMENT '商品ID',
  sku_name VARCHAR(255) NOT NULL COMMENT 'SKU名称',
  sale_price DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '售价',
  original_price DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '划线价',
  sku_attrs JSON NULL COMMENT '规格属性',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED, DISABLED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_skus_no (sku_no),
  KEY idx_skus_product (product_id),
  CONSTRAINT fk_skus_product FOREIGN KEY (product_id) REFERENCES products (id),
  CHECK (sale_price >= 0),
  CHECK (original_price >= 0),
  CHECK (sale_price <= original_price)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品SKU表';

CREATE TABLE IF NOT EXISTS sku_inventories (
  id BIGINT NOT NULL COMMENT '库存ID',
  sku_id BIGINT NOT NULL COMMENT 'SKU ID',
  total_stock INT NOT NULL DEFAULT 0 COMMENT '总库存',
  locked_stock INT NOT NULL DEFAULT 0 COMMENT '锁定库存',
  available_stock INT NOT NULL DEFAULT 0 COMMENT '可售库存',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED, DISABLED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_inventory_sku (sku_id),
  CONSTRAINT fk_inventory_sku FOREIGN KEY (sku_id) REFERENCES product_skus (id),
  CHECK (total_stock >= 0),
  CHECK (locked_stock >= 0),
  CHECK (available_stock >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SKU库存表';

CREATE TABLE IF NOT EXISTS product_audit_records (
  id BIGINT NOT NULL COMMENT '商品审核记录ID',
  product_id BIGINT NOT NULL COMMENT '商品ID',
  merchant_id BIGINT NOT NULL COMMENT '商家ID',
  audit_status VARCHAR(32) NOT NULL COMMENT 'APPROVED, REJECTED',
  audit_user_id BIGINT NOT NULL COMMENT '审核人用户ID',
  audit_reason VARCHAR(500) NULL COMMENT '审核意见',
  audited_at DATETIME(3) NOT NULL COMMENT '审核时间',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  KEY idx_product_audit_product (product_id),
  KEY idx_product_audit_merchant (merchant_id),
  KEY idx_product_audit_user (audit_user_id),
  CONSTRAINT fk_product_audit_product FOREIGN KEY (product_id) REFERENCES products (id),
  CONSTRAINT fk_product_audit_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id),
  CONSTRAINT fk_product_audit_user FOREIGN KEY (audit_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品审核记录表';

CREATE TABLE IF NOT EXISTS carts (
  id BIGINT NOT NULL COMMENT '购物车ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  store_id BIGINT NOT NULL COMMENT '店铺ID',
  product_id BIGINT NOT NULL COMMENT '商品ID',
  sku_id BIGINT NOT NULL COMMENT 'SKU ID',
  quantity INT NOT NULL DEFAULT 1 COMMENT '购买数量',
  checked TINYINT NOT NULL DEFAULT 1 COMMENT '是否选中',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED, DISABLED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_cart_user_sku (user_id, sku_id),
  KEY idx_cart_store (store_id),
  CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_cart_store FOREIGN KEY (store_id) REFERENCES stores (id),
  CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES products (id),
  CONSTRAINT fk_cart_sku FOREIGN KEY (sku_id) REFERENCES product_skus (id),
  CHECK (quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='购物车表';

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT NOT NULL COMMENT '订单ID',
  order_no VARCHAR(64) NOT NULL COMMENT '订单号',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  merchant_id BIGINT NOT NULL COMMENT '商家ID',
  store_id BIGINT NOT NULL COMMENT '店铺ID',
  order_status VARCHAR(32) NOT NULL DEFAULT 'CREATED' COMMENT 'CREATED, PAID, SHIPPED, COMPLETED, CANCELED, REFUNDING, CLOSED',
  pay_status VARCHAR(32) NOT NULL DEFAULT 'UNPAID' COMMENT 'UNPAID, PAID, REFUNDED, PART_REFUNDED',
  total_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '商品总额',
  freight_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '运费',
  discount_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '优惠金额，P0默认0',
  payable_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '应付金额',
  paid_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '实付金额',
  receiver_snapshot JSON NOT NULL COMMENT '收货信息快照',
  paid_at DATETIME(3) NULL COMMENT '支付时间',
  shipped_at DATETIME(3) NULL COMMENT '发货时间',
  completed_at DATETIME(3) NULL COMMENT '完成时间',
  canceled_at DATETIME(3) NULL COMMENT '取消时间',
  cancel_reason VARCHAR(255) NULL COMMENT '取消原因',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_orders_no (order_no),
  KEY idx_orders_user_status (user_id, order_status),
  KEY idx_orders_store_status (store_id, order_status),
  KEY idx_orders_merchant_time (merchant_id, created_at),
  KEY idx_orders_pay_status (pay_status),
  KEY idx_orders_status_created (order_status, created_at),
  KEY idx_orders_merchant_status_time (merchant_id, order_status, created_at),
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_orders_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id),
  CONSTRAINT fk_orders_store FOREIGN KEY (store_id) REFERENCES stores (id),
  CHECK (total_amount >= 0),
  CHECK (freight_amount >= 0),
  CHECK (discount_amount >= 0),
  CHECK (payable_amount >= 0),
  CHECK (paid_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单主表';

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT NOT NULL COMMENT '订单明细ID',
  order_id BIGINT NOT NULL COMMENT '订单ID',
  order_no VARCHAR(64) NOT NULL COMMENT '订单号',
  product_id BIGINT NOT NULL COMMENT '商品ID',
  sku_id BIGINT NOT NULL COMMENT 'SKU ID',
  product_snapshot JSON NOT NULL COMMENT '商品快照',
  quantity INT NOT NULL COMMENT '购买数量',
  sale_price DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '成交单价',
  total_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '明细总额',
  refund_status VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT 'NONE, REFUNDING, REFUNDED, PART_REFUNDED',
  refunded_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '已退款金额',
  refundable_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '可退金额',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED, DISABLED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  KEY idx_order_items_order (order_id),
  KEY idx_order_items_order_no (order_no),
  KEY idx_order_items_sku (sku_id),
  KEY idx_order_items_product (product_id),
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
  CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
  CONSTRAINT fk_order_items_sku FOREIGN KEY (sku_id) REFERENCES product_skus (id),
  CHECK (quantity > 0),
  CHECK (sale_price >= 0),
  CHECK (total_amount >= 0),
  CHECK (refunded_amount >= 0),
  CHECK (refundable_amount >= 0),
  CHECK (refunded_amount <= refundable_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单明细表';

CREATE TABLE IF NOT EXISTS order_status_logs (
  id BIGINT NOT NULL COMMENT '订单状态日志ID',
  order_id BIGINT NOT NULL COMMENT '订单ID',
  order_no VARCHAR(64) NOT NULL COMMENT '订单号',
  from_status VARCHAR(32) NULL COMMENT '原状态',
  to_status VARCHAR(32) NOT NULL COMMENT '新状态',
  operator_type VARCHAR(32) NOT NULL COMMENT 'USER, MERCHANT, PLATFORM, SYSTEM',
  operator_id BIGINT NULL COMMENT '操作人ID',
  reason VARCHAR(500) NULL COMMENT '原因',
  request_id VARCHAR(64) NULL COMMENT '请求ID',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  KEY idx_order_status_logs_order (order_id),
  KEY idx_order_status_logs_request (request_id),
  CONSTRAINT fk_order_status_logs_order FOREIGN KEY (order_id) REFERENCES orders (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单状态日志表';

CREATE TABLE IF NOT EXISTS payment_orders (
  id BIGINT NOT NULL COMMENT '支付单ID',
  payment_no VARCHAR(64) NOT NULL COMMENT '支付单号',
  order_id BIGINT NOT NULL COMMENT '订单ID',
  order_no VARCHAR(64) NOT NULL COMMENT '订单号',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  channel VARCHAR(32) NOT NULL COMMENT '支付渠道',
  pay_amount DECIMAL(18,2) NOT NULL COMMENT '支付金额',
  pay_status VARCHAR(32) NOT NULL DEFAULT 'INIT' COMMENT 'INIT, PAYING, SUCCESS, FAILED, CLOSED',
  third_trade_no VARCHAR(128) NULL COMMENT '第三方交易号',
  idempotent_key VARCHAR(128) NULL COMMENT '幂等Key',
  paid_at DATETIME(3) NULL COMMENT '支付成功时间',
  callback_payload JSON NULL COMMENT '回调摘要',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_payment_no (payment_no),
  UNIQUE KEY uk_payment_order (order_id),
  UNIQUE KEY uk_payment_idempotent (idempotent_key),
  UNIQUE KEY uk_payment_third_trade (channel, third_trade_no),
  KEY idx_payment_status (pay_status),
  KEY idx_payment_channel_status (channel, pay_status),
  KEY idx_payment_user (user_id),
  CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders (id),
  CONSTRAINT fk_payment_user FOREIGN KEY (user_id) REFERENCES users (id),
  CHECK (pay_amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='支付单表';

CREATE TABLE IF NOT EXISTS after_sales (
  id BIGINT NOT NULL COMMENT '售后单ID',
  after_sale_no VARCHAR(64) NOT NULL COMMENT '售后单号',
  order_id BIGINT NOT NULL COMMENT '订单ID',
  order_item_id BIGINT NULL COMMENT '订单项ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  merchant_id BIGINT NOT NULL COMMENT '商家ID',
  type VARCHAR(32) NOT NULL COMMENT 'REFUND_ONLY, RETURN_REFUND',
  status VARCHAR(32) NOT NULL DEFAULT 'APPLYING' COMMENT 'APPLYING, MERCHANT_APPROVED, MERCHANT_REJECTED, USER_RETURNED, PLATFORM_INTERVENING, CLOSED, COMPLETED',
  apply_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '申请退款金额',
  approved_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '同意退款金额',
  reason VARCHAR(255) NOT NULL COMMENT '申请原因',
  description VARCHAR(1000) NULL COMMENT '说明',
  evidence_urls JSON NULL COMMENT '凭证图片',
  merchant_reason VARCHAR(500) NULL COMMENT '商家处理意见',
  platform_reason VARCHAR(500) NULL COMMENT '平台处理意见',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_after_sale_no (after_sale_no),
  KEY idx_after_sales_order (order_id),
  KEY idx_after_sales_order_item (order_item_id),
  KEY idx_after_sales_merchant_status (merchant_id, status),
  KEY idx_after_sales_user (user_id),
  CONSTRAINT fk_after_sales_order FOREIGN KEY (order_id) REFERENCES orders (id),
  CONSTRAINT fk_after_sales_order_item FOREIGN KEY (order_item_id) REFERENCES order_items (id),
  CONSTRAINT fk_after_sales_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_after_sales_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id),
  CHECK (apply_amount >= 0),
  CHECK (approved_amount >= 0),
  CHECK (approved_amount <= apply_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='售后单表';

CREATE TABLE IF NOT EXISTS return_shipments (
  id BIGINT NOT NULL COMMENT '退货物流ID',
  after_sale_id BIGINT NOT NULL COMMENT '售后单ID',
  logistics_company VARCHAR(64) NOT NULL COMMENT '物流公司',
  tracking_no VARCHAR(128) NOT NULL COMMENT '运单号',
  shipped_at DATETIME(3) NULL COMMENT '用户退货时间',
  received_at DATETIME(3) NULL COMMENT '商家收货时间',
  status VARCHAR(32) NOT NULL DEFAULT 'SHIPPED' COMMENT 'SHIPPED, RECEIVED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_return_after_sale (after_sale_id),
  KEY idx_return_tracking (tracking_no),
  CONSTRAINT fk_return_after_sale FOREIGN KEY (after_sale_id) REFERENCES after_sales (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='退货物流表';

CREATE TABLE IF NOT EXISTS refund_orders (
  id BIGINT NOT NULL COMMENT '退款单ID',
  refund_no VARCHAR(64) NOT NULL COMMENT '退款单号',
  payment_id BIGINT NOT NULL COMMENT '支付单ID',
  payment_no VARCHAR(64) NOT NULL COMMENT '支付单号',
  order_id BIGINT NOT NULL COMMENT '订单ID',
  after_sale_id BIGINT NOT NULL COMMENT '售后单ID',
  refund_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '退款金额',
  refund_status VARCHAR(32) NOT NULL DEFAULT 'INIT' COMMENT 'INIT, PROCESSING, SUCCESS, FAILED',
  channel VARCHAR(32) NOT NULL COMMENT '退款渠道',
  third_refund_no VARCHAR(128) NULL COMMENT '第三方退款号',
  idempotent_key VARCHAR(128) NULL COMMENT '幂等Key',
  fail_reason VARCHAR(500) NULL COMMENT '失败原因',
  refunded_at DATETIME(3) NULL COMMENT '退款成功时间',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_refund_no (refund_no),
  UNIQUE KEY uk_refund_idempotent (idempotent_key),
  KEY idx_refund_order (order_id),
  KEY idx_refund_after_sale (after_sale_id),
  KEY idx_refund_status (refund_status),
  KEY idx_refund_payment_no (payment_no),
  CONSTRAINT fk_refund_payment FOREIGN KEY (payment_id) REFERENCES payment_orders (id),
  CONSTRAINT fk_refund_order FOREIGN KEY (order_id) REFERENCES orders (id),
  CONSTRAINT fk_refund_after_sale FOREIGN KEY (after_sale_id) REFERENCES after_sales (id),
  CHECK (refund_amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='退款单表';

CREATE TABLE IF NOT EXISTS order_shipments (
  id BIGINT NOT NULL COMMENT '发货物流ID',
  order_id BIGINT NOT NULL COMMENT '订单ID',
  order_no VARCHAR(64) NOT NULL COMMENT '订单号',
  merchant_id BIGINT NOT NULL COMMENT '商家ID',
  logistics_company VARCHAR(64) NOT NULL COMMENT '物流公司',
  tracking_no VARCHAR(128) NOT NULL COMMENT '运单号',
  shipped_by BIGINT NOT NULL COMMENT '发货操作人ID',
  shipped_at DATETIME(3) NOT NULL COMMENT '发货时间',
  status VARCHAR(32) NOT NULL DEFAULT 'SHIPPED' COMMENT 'SHIPPED, SIGNED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_shipment_order (order_id),
  KEY idx_shipment_tracking (tracking_no),
  KEY idx_shipment_merchant (merchant_id),
  CONSTRAINT fk_shipment_order FOREIGN KEY (order_id) REFERENCES orders (id),
  CONSTRAINT fk_shipment_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id),
  CONSTRAINT fk_shipment_user FOREIGN KEY (shipped_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='订单发货物流表';

CREATE TABLE IF NOT EXISTS merchant_settlement_accounts (
  id BIGINT NOT NULL COMMENT '结算账户ID',
  merchant_id BIGINT NOT NULL COMMENT '商家ID',
  account_type VARCHAR(32) NOT NULL COMMENT 'BANK_CARD, ALIPAY, WECHAT',
  account_name VARCHAR(128) NOT NULL COMMENT '收款户名',
  account_no_encrypted VARCHAR(512) NOT NULL COMMENT '加密账号',
  account_no_masked VARCHAR(64) NOT NULL COMMENT '脱敏账号',
  bank_name VARCHAR(128) NULL COMMENT '银行名称',
  audit_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, APPROVED, REJECTED',
  status VARCHAR(32) NOT NULL DEFAULT 'DISABLED' COMMENT 'ENABLED, DISABLED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  KEY idx_settlement_account_merchant (merchant_id),
  KEY idx_settlement_account_status (audit_status, status),
  CONSTRAINT fk_settlement_account_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商家结算账户表';

CREATE TABLE IF NOT EXISTS merchant_bills (
  id BIGINT NOT NULL COMMENT '商家账单ID',
  merchant_id BIGINT NOT NULL COMMENT '商家ID',
  bill_date DATE NOT NULL COMMENT '账单日期',
  order_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '订单收入',
  freight_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '运费',
  refund_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '退款金额',
  commission_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '平台佣金',
  adjustment_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '调整金额',
  payable_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '应结金额',
  status VARCHAR(32) NOT NULL DEFAULT 'GENERATED' COMMENT 'GENERATED, CONFIRMED, SETTLED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_merchant_bill_date (merchant_id, bill_date),
  KEY idx_merchant_bills_status (status),
  CONSTRAINT fk_merchant_bills_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商家日账单表';

CREATE TABLE IF NOT EXISTS settlement_orders (
  id BIGINT NOT NULL COMMENT '结算单ID',
  settlement_no VARCHAR(64) NOT NULL COMMENT '结算单号',
  merchant_id BIGINT NOT NULL COMMENT '商家ID',
  start_date DATE NOT NULL COMMENT '结算开始日',
  end_date DATE NOT NULL COMMENT '结算结束日',
  order_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '订单金额',
  refund_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '退款冲账',
  commission_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '平台佣金',
  frozen_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '冻结金额',
  payable_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '应付金额',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING_AUDIT' COMMENT 'PENDING_AUDIT, APPROVED, REJECTED, PAID',
  audit_user_id BIGINT NULL COMMENT '审核人ID',
  audit_reason VARCHAR(500) NULL COMMENT '审核意见',
  approved_at DATETIME(3) NULL COMMENT '审核时间',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_settlement_no (settlement_no),
  UNIQUE KEY uk_settlement_merchant_cycle (merchant_id, start_date, end_date),
  KEY idx_settlement_status (status),
  KEY idx_settlement_audit_user (audit_user_id),
  CONSTRAINT fk_settlement_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id),
  CONSTRAINT fk_settlement_audit_user FOREIGN KEY (audit_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='结算单表';

CREATE TABLE IF NOT EXISTS settlement_order_items (
  id BIGINT NOT NULL COMMENT '结算明细ID',
  settlement_id BIGINT NOT NULL COMMENT '结算单ID',
  merchant_id BIGINT NOT NULL COMMENT '商家ID',
  order_id BIGINT NOT NULL COMMENT '订单ID',
  order_item_id BIGINT NOT NULL COMMENT '订单项ID',
  bill_id BIGINT NULL COMMENT '商家账单ID',
  payable_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '明细应结金额',
  commission_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '明细佣金',
  refund_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '明细退款',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED, DISABLED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_settlement_item_order_item (settlement_id, order_item_id),
  KEY idx_settlement_items_order (order_id),
  KEY idx_settlement_items_merchant (merchant_id),
  KEY idx_settlement_items_bill (bill_id),
  CONSTRAINT fk_settlement_item_settlement FOREIGN KEY (settlement_id) REFERENCES settlement_orders (id),
  CONSTRAINT fk_settlement_item_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id),
  CONSTRAINT fk_settlement_item_order FOREIGN KEY (order_id) REFERENCES orders (id),
  CONSTRAINT fk_settlement_item_order_item FOREIGN KEY (order_item_id) REFERENCES order_items (id),
  CONSTRAINT fk_settlement_item_bill FOREIGN KEY (bill_id) REFERENCES merchant_bills (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='结算明细表';

CREATE TABLE IF NOT EXISTS withdraw_orders (
  id BIGINT NOT NULL COMMENT '提现单ID',
  withdraw_no VARCHAR(64) NOT NULL COMMENT '提现单号',
  merchant_id BIGINT NOT NULL COMMENT '商家ID',
  account_id BIGINT NOT NULL COMMENT '结算账户ID',
  settlement_id BIGINT NULL COMMENT '结算单ID',
  amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '提现金额',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING_AUDIT' COMMENT 'PENDING_AUDIT, APPROVED, REJECTED, PAYING, SUCCESS, FAILED',
  audit_user_id BIGINT NULL COMMENT '审核人ID',
  audit_reason VARCHAR(500) NULL COMMENT '审核意见',
  fail_reason VARCHAR(500) NULL COMMENT '打款失败原因',
  paid_at DATETIME(3) NULL COMMENT '打款成功时间',
  idempotent_key VARCHAR(128) NULL COMMENT '幂等Key',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_withdraw_no (withdraw_no),
  UNIQUE KEY uk_withdraw_idempotent (idempotent_key),
  KEY idx_withdraw_merchant_status (merchant_id, status),
  KEY idx_withdraw_account (account_id),
  KEY idx_withdraw_settlement (settlement_id),
  KEY idx_withdraw_audit_user (audit_user_id),
  CONSTRAINT fk_withdraw_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id),
  CONSTRAINT fk_withdraw_account FOREIGN KEY (account_id) REFERENCES merchant_settlement_accounts (id),
  CONSTRAINT fk_withdraw_settlement FOREIGN KEY (settlement_id) REFERENCES settlement_orders (id),
  CONSTRAINT fk_withdraw_audit_user FOREIGN KEY (audit_user_id) REFERENCES users (id),
  CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='提现单表';

CREATE TABLE IF NOT EXISTS account_flow_records (
  id BIGINT NOT NULL COMMENT '账务流水ID',
  flow_no VARCHAR(64) NOT NULL COMMENT '流水号',
  merchant_id BIGINT NOT NULL COMMENT '商家ID',
  biz_type VARCHAR(32) NOT NULL COMMENT 'ORDER, REFUND, COMMISSION, SETTLEMENT, WITHDRAW, FREEZE, ADJUST',
  biz_no VARCHAR(64) NOT NULL COMMENT '业务单号',
  direction VARCHAR(32) NOT NULL COMMENT 'IN, OUT, FREEZE, UNFREEZE',
  amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '发生金额',
  balance_before DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '变动前余额',
  balance_after DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '变动后余额',
  frozen_after DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '变动后冻结金额',
  status VARCHAR(32) NOT NULL DEFAULT 'SUCCESS' COMMENT 'SUCCESS, FAILED',
  occurred_at DATETIME(3) NOT NULL COMMENT '发生时间',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_flow_no (flow_no),
  KEY idx_flow_biz (biz_type, biz_no, direction),
  KEY idx_flow_merchant_time (merchant_id, occurred_at),
  CONSTRAINT fk_flow_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id),
  CHECK (amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='账务流水表';

CREATE TABLE IF NOT EXISTS reconciliation_records (
  id BIGINT NOT NULL COMMENT '对账记录ID',
  reconcile_no VARCHAR(64) NOT NULL COMMENT '对账编号',
  channel VARCHAR(32) NOT NULL COMMENT '支付渠道',
  bill_date DATE NOT NULL COMMENT '对账日期',
  biz_type VARCHAR(32) NOT NULL COMMENT 'PAYMENT, REFUND',
  biz_no VARCHAR(64) NOT NULL COMMENT '平台业务单号',
  third_trade_no VARCHAR(128) NULL COMMENT '渠道交易号',
  platform_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '平台金额',
  channel_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00 COMMENT '渠道金额',
  diff_type VARCHAR(32) NOT NULL DEFAULT 'NONE' COMMENT 'NONE, PLATFORM_MISSING, CHANNEL_MISSING, AMOUNT_DIFF',
  handle_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, PROCESSING, RESOLVED',
  handle_result VARCHAR(500) NULL COMMENT '处理结果',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_reconcile_no (reconcile_no),
  KEY idx_reconcile_channel_date (channel, bill_date),
  KEY idx_reconcile_handle (handle_status, diff_type),
  KEY idx_reconcile_biz (biz_type, biz_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='对账记录表';

CREATE TABLE IF NOT EXISTS exception_orders (
  id BIGINT NOT NULL COMMENT '异常单ID',
  exception_no VARCHAR(64) NOT NULL COMMENT '异常单号',
  exception_type VARCHAR(32) NOT NULL COMMENT 'ORDER, PAYMENT, REFUND, STOCK, RECONCILE',
  biz_no VARCHAR(64) NOT NULL COMMENT '关联业务单号',
  order_id BIGINT NULL COMMENT '订单ID',
  merchant_id BIGINT NULL COMMENT '商家ID',
  severity VARCHAR(32) NOT NULL DEFAULT 'MEDIUM' COMMENT 'LOW, MEDIUM, HIGH',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, PROCESSING, RESOLVED, CLOSED',
  reason VARCHAR(500) NOT NULL COMMENT '异常原因',
  suggestion VARCHAR(500) NULL COMMENT '建议处理动作',
  handle_result VARCHAR(500) NULL COMMENT '处理结果',
  handled_by BIGINT NULL COMMENT '处理人ID',
  handled_at DATETIME(3) NULL COMMENT '处理时间',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_exception_no (exception_no),
  KEY idx_exception_type_status (exception_type, status),
  KEY idx_exception_biz (biz_no),
  KEY idx_exception_merchant (merchant_id),
  KEY idx_exception_order (order_id),
  KEY idx_exception_handled_by (handled_by),
  CONSTRAINT fk_exception_order FOREIGN KEY (order_id) REFERENCES orders (id),
  CONSTRAINT fk_exception_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id),
  CONSTRAINT fk_exception_handled_by FOREIGN KEY (handled_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='异常单表';

CREATE TABLE IF NOT EXISTS idempotent_records (
  id BIGINT NOT NULL COMMENT '幂等记录ID',
  idempotent_key VARCHAR(128) NOT NULL COMMENT '幂等Key',
  request_id VARCHAR(64) NOT NULL COMMENT '请求ID',
  biz_type VARCHAR(32) NOT NULL COMMENT 'ORDER_CREATE, PAY_CALLBACK, REFUND_CREATE, WITHDRAW_CREATE',
  biz_no VARCHAR(64) NULL COMMENT '业务单号',
  request_hash VARCHAR(128) NOT NULL COMMENT '请求参数摘要',
  response_snapshot JSON NULL COMMENT '首次响应摘要',
  status VARCHAR(32) NOT NULL DEFAULT 'PROCESSING' COMMENT 'PROCESSING, SUCCESS, FAILED',
  expired_at DATETIME(3) NOT NULL COMMENT '过期时间',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_idempotent_key (idempotent_key),
  KEY idx_idempotent_request (request_id),
  KEY idx_idempotent_biz (biz_type, biz_no),
  KEY idx_idempotent_expired (expired_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='幂等记录表';

CREATE TABLE IF NOT EXISTS operation_logs (
  id BIGINT NOT NULL COMMENT '操作日志ID',
  request_id VARCHAR(64) NULL COMMENT '请求ID',
  operator_type VARCHAR(32) NOT NULL COMMENT 'USER, MERCHANT, PLATFORM, SYSTEM',
  operator_id BIGINT NULL COMMENT '操作人ID',
  operator_name VARCHAR(64) NULL COMMENT '操作人名称',
  merchant_id BIGINT NULL COMMENT '商家ID',
  module_code VARCHAR(64) NOT NULL COMMENT '模块编码',
  action_code VARCHAR(64) NOT NULL COMMENT '动作编码',
  target_type VARCHAR(64) NULL COMMENT '对象类型',
  target_id VARCHAR(64) NULL COMMENT '对象ID',
  biz_type VARCHAR(64) NULL COMMENT '业务类型',
  biz_no VARCHAR(64) NULL COMMENT '业务单号',
  before_snapshot JSON NULL COMMENT '操作前状态',
  after_snapshot JSON NULL COMMENT '操作后状态',
  request_ip VARCHAR(64) NULL COMMENT '请求IP',
  user_agent VARCHAR(500) NULL COMMENT 'User-Agent',
  result VARCHAR(32) NOT NULL DEFAULT 'SUCCESS' COMMENT 'SUCCESS, FAILED',
  fail_reason VARCHAR(500) NULL COMMENT '失败原因',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  KEY idx_operation_request (request_id),
  KEY idx_operation_operator (operator_type, operator_id),
  KEY idx_operation_biz (biz_type, biz_no),
  KEY idx_operation_merchant (merchant_id),
  KEY idx_operation_target (target_type, target_id),
  KEY idx_operation_module_action_time (module_code, action_code, created_at),
  KEY idx_operation_time (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作日志表';

CREATE TABLE IF NOT EXISTS system_configs (
  id BIGINT NOT NULL COMMENT '配置ID',
  config_key VARCHAR(128) NOT NULL COMMENT '配置键',
  config_value VARCHAR(2000) NOT NULL COMMENT '配置值',
  config_desc VARCHAR(500) NULL COMMENT '配置说明',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'ENABLED, DISABLED',
  remark VARCHAR(500) NULL COMMENT '备注',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL COMMENT '软删除时间',
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  PRIMARY KEY (id),
  UNIQUE KEY uk_config_key (config_key),
  KEY idx_config_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统配置表';

SET FOREIGN_KEY_CHECKS = 1;
