SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT NOT NULL PRIMARY KEY,
  parent_id BIGINT NOT NULL DEFAULT 0,
  category_name VARCHAR(128) NOT NULL,
  level INT NOT NULL DEFAULT 1,
  sort_no INT NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  KEY idx_categories_parent (parent_id),
  KEY idx_categories_status_sort (status, level, sort_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO categories (id, parent_id, category_name, level, sort_no, status)
VALUES
  (1001, 0, '手机数码', 1, 1, 'ENABLED'),
  (1002, 0, '电脑办公', 1, 2, 'ENABLED'),
  (1003, 0, '家用电器', 1, 3, 'ENABLED'),
  (1004, 0, '服装鞋帽', 1, 4, 'ENABLED'),
  (1005, 0, '食品饮料', 1, 5, 'ENABLED'),
  (1006, 0, '美妆个护', 1, 6, 'ENABLED'),
  (1007, 0, '家居生活', 1, 7, 'ENABLED'),
  (1008, 0, '母婴玩具', 1, 8, 'ENABLED'),
  (1009, 0, '图书文具', 1, 9, 'ENABLED'),
  (1010, 0, '运动户外', 1, 10, 'ENABLED'),
  (1101, 1001, '手机', 2, 1, 'ENABLED'),
  (1102, 1001, '平板电脑', 2, 2, 'ENABLED'),
  (1103, 1001, '智能手表', 2, 3, 'ENABLED'),
  (1104, 1001, '耳机音箱', 2, 4, 'ENABLED'),
  (1105, 1001, '手机配件', 2, 5, 'ENABLED'),
  (1201, 1002, '笔记本电脑', 2, 1, 'ENABLED'),
  (1202, 1002, '台式机', 2, 2, 'ENABLED'),
  (1203, 1002, '显示器', 2, 3, 'ENABLED'),
  (1204, 1002, '外设设备', 2, 4, 'ENABLED'),
  (1301, 1003, '厨房电器', 2, 1, 'ENABLED'),
  (1302, 1003, '生活电器', 2, 2, 'ENABLED'),
  (1303, 1003, '个护电器', 2, 3, 'ENABLED'),
  (1401, 1004, '男装', 2, 1, 'ENABLED'),
  (1402, 1004, '女装', 2, 2, 'ENABLED'),
  (1403, 1004, '运动鞋', 2, 3, 'ENABLED'),
  (1404, 1004, '配饰', 2, 4, 'ENABLED'),
  (1501, 1005, '休闲零食', 2, 1, 'ENABLED'),
  (1502, 1005, '饮料冲调', 2, 2, 'ENABLED'),
  (1503, 1005, '茶酒礼品', 2, 3, 'ENABLED'),
  (1601, 1006, '面部护肤', 2, 1, 'ENABLED'),
  (1602, 1006, '彩妆', 2, 2, 'ENABLED'),
  (1603, 1006, '洗发护发', 2, 3, 'ENABLED'),
  (1701, 1007, '家纺布艺', 2, 1, 'ENABLED'),
  (1702, 1007, '厨具餐具', 2, 2, 'ENABLED'),
  (1703, 1007, '收纳清洁', 2, 3, 'ENABLED'),
  (1801, 1008, '婴童用品', 2, 1, 'ENABLED'),
  (1802, 1008, '玩具乐器', 2, 2, 'ENABLED'),
  (1803, 1008, '孕产用品', 2, 3, 'ENABLED'),
  (1901, 1009, '图书', 2, 1, 'ENABLED'),
  (1902, 1009, '文具', 2, 2, 'ENABLED'),
  (1903, 1009, '教辅资料', 2, 3, 'ENABLED'),
  (2001, 1010, '运动装备', 2, 1, 'ENABLED'),
  (2002, 1010, '户外装备', 2, 2, 'ENABLED'),
  (2003, 1010, '健身器材', 2, 3, 'ENABLED')
ON DUPLICATE KEY UPDATE
  parent_id = VALUES(parent_id),
  category_name = VALUES(category_name),
  level = VALUES(level),
  sort_no = VALUES(sort_no),
  status = VALUES(status),
  deleted_at = NULL;

CREATE TABLE IF NOT EXISTS merchant_applications (
  id BIGINT NOT NULL PRIMARY KEY,
  merchant_no VARCHAR(64) NOT NULL,
  owner_user_id BIGINT NOT NULL,
  company_name VARCHAR(255) NOT NULL,
  license_no VARCHAR(128) NOT NULL,
  contact_name VARCHAR(64) NOT NULL,
  contact_mobile VARCHAR(32) NOT NULL,
  audit_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  reject_reason VARCHAR(512) NULL,
  approved_at DATETIME(3) NULL,
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_merchant_applications_no (merchant_no),
  KEY idx_merchant_applications_owner (owner_user_id),
  KEY idx_merchant_applications_audit (audit_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS stores (
  id BIGINT NOT NULL PRIMARY KEY,
  merchant_id BIGINT NOT NULL,
  store_no VARCHAR(64) NOT NULL,
  store_name VARCHAR(128) NOT NULL,
  logo_url VARCHAR(512) NULL,
  contact_mobile VARCHAR(32) NULL,
  category_id BIGINT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_stores_no (store_no),
  KEY idx_stores_merchant (merchant_id),
  KEY idx_stores_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS merchant_staffs (
  id BIGINT NOT NULL PRIMARY KEY,
  merchant_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  staff_name VARCHAR(64) NOT NULL,
  role_type VARCHAR(32) NOT NULL,
  menu_permissions TEXT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  last_login_at DATETIME(3) NULL DEFAULT NULL COMMENT '最后登录时间',
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  KEY idx_merchant_staffs_merchant (merchant_id),
  KEY idx_merchant_staffs_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS merchant_settlement_accounts (
  id BIGINT NOT NULL PRIMARY KEY,
  merchant_id BIGINT NOT NULL,
  account_type VARCHAR(32) NOT NULL,
  account_name VARCHAR(128) NOT NULL,
  account_no VARCHAR(128) NOT NULL,
  bank_name VARCHAR(128) NULL,
  audit_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  KEY idx_settlement_accounts_merchant (merchant_id),
  KEY idx_settlement_accounts_audit (audit_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT NOT NULL PRIMARY KEY,
  product_no VARCHAR(64) NOT NULL,
  merchant_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  category_id BIGINT NULL,
  product_name VARCHAR(255) NOT NULL,
  main_image_url VARCHAR(512) NULL,
  detail_html MEDIUMTEXT NULL,
  price DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  stock_total INT NOT NULL DEFAULT 0,
  audit_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  sale_status VARCHAR(32) NOT NULL DEFAULT 'OFF_SALE',
  reject_reason VARCHAR(512) NULL,
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_products_no (product_no),
  KEY idx_products_merchant (merchant_id),
  KEY idx_products_category (category_id),
  KEY idx_products_sale_audit (audit_status, sale_status),
  FULLTEXT KEY ft_products_name (product_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS carts (
  id BIGINT NOT NULL PRIMARY KEY,
  user_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  sku_id BIGINT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  checked TINYINT NOT NULL DEFAULT 1,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  KEY idx_carts_user (user_id),
  KEY idx_carts_user_sku (user_id, sku_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT NOT NULL PRIMARY KEY,
  order_no VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  merchant_id BIGINT NOT NULL,
  store_id BIGINT NOT NULL,
  order_status VARCHAR(32) NOT NULL,
  pay_status VARCHAR(32) NOT NULL,
  total_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  freight_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  payable_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  paid_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  receiver_snapshot TEXT NULL,
  paid_at DATETIME(3) NULL,
  shipped_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  canceled_at DATETIME(3) NULL,
  cancel_reason VARCHAR(512) NULL,
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_orders_no (order_no),
  KEY idx_orders_user (user_id),
  KEY idx_orders_merchant (merchant_id),
  KEY idx_orders_status_pay (order_status, pay_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT NOT NULL PRIMARY KEY,
  order_id BIGINT NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  product_id BIGINT NOT NULL,
  sku_id BIGINT NOT NULL,
  product_snapshot TEXT NULL,
  quantity INT NOT NULL DEFAULT 1,
  sale_price DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  refund_status VARCHAR(32) NOT NULL DEFAULT 'NONE',
  refunded_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  refundable_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  KEY idx_order_items_order (order_id),
  KEY idx_order_items_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS order_status_logs (
  id BIGINT NOT NULL PRIMARY KEY,
  order_id BIGINT NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  from_status VARCHAR(32) NULL,
  to_status VARCHAR(32) NOT NULL,
  operator_type VARCHAR(32) NOT NULL,
  operator_id BIGINT NULL,
  reason VARCHAR(512) NULL,
  request_id VARCHAR(128) NULL,
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  KEY idx_order_status_logs_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS payment_orders (
  id BIGINT NOT NULL PRIMARY KEY,
  payment_no VARCHAR(64) NOT NULL,
  order_id BIGINT NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  channel VARCHAR(32) NOT NULL,
  pay_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  pay_status VARCHAR(32) NOT NULL,
  third_trade_no VARCHAR(128) NULL,
  idempotent_key VARCHAR(128) NULL,
  paid_at DATETIME(3) NULL,
  callback_payload MEDIUMTEXT NULL,
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_payment_orders_no (payment_no),
  KEY idx_payment_orders_order (order_id),
  KEY idx_payment_orders_idempotent (idempotent_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS refund_orders (
  id BIGINT NOT NULL PRIMARY KEY,
  refund_no VARCHAR(64) NOT NULL,
  payment_id BIGINT NOT NULL,
  payment_no VARCHAR(64) NOT NULL,
  order_id BIGINT NOT NULL,
  after_sale_id BIGINT NULL,
  refund_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  refund_status VARCHAR(32) NOT NULL,
  channel VARCHAR(32) NOT NULL,
  third_refund_no VARCHAR(128) NULL,
  idempotent_key VARCHAR(128) NULL,
  fail_reason VARCHAR(512) NULL,
  refunded_at DATETIME(3) NULL,
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_refund_orders_no (refund_no),
  KEY idx_refund_orders_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS after_sales (
  id BIGINT NOT NULL PRIMARY KEY,
  after_sale_no VARCHAR(64) NOT NULL,
  order_id BIGINT NOT NULL,
  order_item_id BIGINT NULL,
  user_id BIGINT NOT NULL,
  merchant_id BIGINT NOT NULL,
  type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  apply_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  approved_amount DECIMAL(18,2) NULL,
  reason VARCHAR(512) NULL,
  description TEXT NULL,
  evidence_urls TEXT NULL,
  merchant_reason VARCHAR(512) NULL,
  platform_reason VARCHAR(512) NULL,
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_after_sales_no (after_sale_no),
  KEY idx_after_sales_order (order_id),
  KEY idx_after_sales_user (user_id),
  KEY idx_after_sales_merchant_status (merchant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS order_shipments (
  id BIGINT NOT NULL PRIMARY KEY,
  order_id BIGINT NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  merchant_id BIGINT NOT NULL,
  logistics_company VARCHAR(128) NOT NULL,
  tracking_no VARCHAR(128) NOT NULL,
  shipped_by BIGINT NULL,
  shipped_at DATETIME(3) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'SHIPPED',
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  KEY idx_order_shipments_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS return_shipments (
  id BIGINT NOT NULL PRIMARY KEY,
  after_sale_id BIGINT NOT NULL,
  logistics_company VARCHAR(128) NOT NULL,
  tracking_no VARCHAR(128) NOT NULL,
  shipped_at DATETIME(3) NULL,
  received_at DATETIME(3) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'SHIPPED',
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  KEY idx_return_shipments_after_sale (after_sale_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS merchant_bills (
  id BIGINT NOT NULL PRIMARY KEY,
  merchant_id BIGINT NOT NULL,
  bill_date DATE NOT NULL,
  order_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  freight_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  refund_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  commission_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  adjustment_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  payable_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  status VARCHAR(32) NOT NULL DEFAULT 'GENERATED',
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  KEY idx_merchant_bills_merchant_date (merchant_id, bill_date),
  KEY idx_merchant_bills_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS settlement_orders (
  id BIGINT NOT NULL PRIMARY KEY,
  settlement_no VARCHAR(64) NOT NULL,
  merchant_id BIGINT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  order_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  refund_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  commission_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  frozen_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  payable_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING_AUDIT',
  audit_user_id BIGINT NULL,
  audit_reason VARCHAR(512) NULL,
  approved_at DATETIME(3) NULL,
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_settlement_orders_no (settlement_no),
  KEY idx_settlement_orders_merchant (merchant_id),
  KEY idx_settlement_orders_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS settlement_order_items (
  id BIGINT NOT NULL PRIMARY KEY,
  settlement_id BIGINT NOT NULL,
  merchant_id BIGINT NOT NULL,
  order_id BIGINT NOT NULL,
  order_item_id BIGINT NULL,
  bill_id BIGINT NULL,
  payable_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  commission_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  refund_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  KEY idx_settlement_items_settlement (settlement_id),
  KEY idx_settlement_items_merchant (merchant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS withdraw_orders (
  id BIGINT NOT NULL PRIMARY KEY,
  withdraw_no VARCHAR(64) NOT NULL,
  merchant_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  settlement_id BIGINT NULL,
  amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING_AUDIT',
  audit_user_id BIGINT NULL,
  audit_reason VARCHAR(512) NULL,
  fail_reason VARCHAR(512) NULL,
  paid_at DATETIME(3) NULL,
  idempotent_key VARCHAR(128) NULL,
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_withdraw_orders_no (withdraw_no),
  KEY idx_withdraw_orders_merchant (merchant_id),
  KEY idx_withdraw_orders_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS account_flow_records (
  id BIGINT NOT NULL PRIMARY KEY,
  flow_no VARCHAR(64) NOT NULL,
  merchant_id BIGINT NOT NULL,
  biz_type VARCHAR(32) NOT NULL,
  biz_no VARCHAR(64) NOT NULL,
  direction VARCHAR(32) NOT NULL,
  amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  balance_before DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  balance_after DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  frozen_after DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  status VARCHAR(32) NOT NULL DEFAULT 'SUCCESS',
  occurred_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_account_flow_records_no (flow_no),
  KEY idx_account_flow_records_merchant (merchant_id),
  KEY idx_account_flow_records_biz (biz_type, biz_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS reconciliation_records (
  id BIGINT NOT NULL PRIMARY KEY,
  reconcile_no VARCHAR(64) NOT NULL,
  channel VARCHAR(32) NOT NULL,
  bill_date DATE NOT NULL,
  biz_type VARCHAR(32) NOT NULL,
  biz_no VARCHAR(64) NOT NULL,
  third_trade_no VARCHAR(128) NULL,
  platform_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  channel_amount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  diff_type VARCHAR(32) NOT NULL DEFAULT 'NONE',
  handle_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  handle_result VARCHAR(512) NULL,
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_reconciliation_records_no (reconcile_no),
  KEY idx_reconciliation_records_channel_date (channel, bill_date),
  KEY idx_reconciliation_records_status (handle_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS operation_logs (
  id BIGINT NOT NULL PRIMARY KEY,
  request_id VARCHAR(128) NULL,
  operator_type VARCHAR(32) NOT NULL,
  operator_id BIGINT NULL,
  operator_name VARCHAR(128) NULL,
  merchant_id BIGINT NULL,
  module_code VARCHAR(64) NOT NULL,
  action_code VARCHAR(64) NOT NULL,
  target_type VARCHAR(64) NULL,
  target_id VARCHAR(128) NULL,
  biz_type VARCHAR(64) NULL,
  biz_no VARCHAR(128) NULL,
  before_snapshot MEDIUMTEXT NULL,
  after_snapshot MEDIUMTEXT NULL,
  request_ip VARCHAR(64) NULL,
  user_agent VARCHAR(512) NULL,
  result VARCHAR(32) NOT NULL DEFAULT 'SUCCESS',
  fail_reason VARCHAR(512) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  KEY idx_operation_logs_module_action (module_code, action_code),
  KEY idx_operation_logs_biz (biz_type, biz_no),
  KEY idx_operation_logs_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS exception_orders (
  id BIGINT NOT NULL PRIMARY KEY,
  exception_no VARCHAR(64) NOT NULL,
  exception_type VARCHAR(32) NOT NULL,
  biz_no VARCHAR(128) NULL,
  order_id BIGINT NULL,
  merchant_id BIGINT NULL,
  severity VARCHAR(32) NOT NULL DEFAULT 'MEDIUM',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  reason VARCHAR(512) NULL,
  suggestion VARCHAR(512) NULL,
  handle_result VARCHAR(512) NULL,
  handled_by BIGINT NULL,
  handled_at DATETIME(3) NULL,
  remark VARCHAR(512) NULL,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_exception_orders_no (exception_no),
  KEY idx_exception_orders_type (exception_type),
  KEY idx_exception_orders_status (status),
  KEY idx_exception_orders_merchant (merchant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
