server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

spring:
  flyway:
    clean-disabled: true

logging:
  level:
    root: INFO
    com.youxuan.platform: INFO
